version: '3.2'
services:
  postgres:
    container_name: clair_db
    image: arminc/clair-db:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair
    image: arminc/clair-local-scan:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060:6060"
    links:
      - postgres